from crisis_models import Mental_Health_Center, State, County 
from app import db


db.drop_all()
db.create_all()

texas = State(name='Texas')
db.session.add(texas)
db.session.commit()

mental_health_centers = [
Mental_Health_Center(name='Access', website='http://www.accessmhmr.org/', crisis_line='800-621-1693', state_id= 1),
Mental_Health_Center(name='North Texas Behavioral Health Authority', website='https://www.ntbha.org/', crisis_line='866-260-8000', state_id=1),
Mental_Health_Center(name='Austin Travis County Integral Care', website='https://www.integralcare.org/en/home/', crisis_line='512-472-4357', state_id=1),
Mental_Health_Center(name='Heart of Texas Region MHMR Center', website='https://www.hotrmhmr.org/', crisis_line='866-752-3451', state_id=1),
Mental_Health_Center(name='MHMR Authority of Brazos Valley', website='https://www.mhmrabv.org/', crisis_line='888-522-8262', state_id=1),
Mental_Health_Center(name='MHMR Authority of Harris County', website='https://www.theharriscenter.org/', crisis_line='866-970-4770', state_id=1),
Mental_Health_Center(name='Center for Life Resources', website='http://www.cflr.us/ns/', crisis_line='800-458-7788', state_id=1),
Mental_Health_Center(name='Denton County MHMR Center', website='http://www.dentonmhmr.org/', crisis_line='800-762-0157', state_id=1),
Mental_Health_Center(name='Emergence Health Network', website='https://www.emergencehealthnetwork.org/', crisis_line='877-562-6467', state_id=1),
Mental_Health_Center(name='MHMR of Tarrant County', website='https://www.mhmrtarrant.org/', crisis_line='800-866-2465', state_id=1),
Mental_Health_Center(name='Community Healthcore', website='http://www.communityhealthcore.com/', crisis_line='800-832-1009', state_id=1),
Mental_Health_Center(name='Andrews Center', website='http://www.andrewscenter.com/', crisis_line='877-934-2131', state_id=1),
Mental_Health_Center(name='Betty Hardwick', website='https://www.bettyhardwick.org/', crisis_line='800-758-3344', state_id=1),
Mental_Health_Center(name='Bluebonnet Trails', website='http://www.bbtrails.org/', crisis_line='800-841-1255', state_id=1),
Mental_Health_Center(name='Border Region', website='http://www.borderregion.org/', crisis_line='800-643-1102', state_id=1),
Mental_Health_Center(name='Camino Real', website='http://www.caminorealcs.org/', crisis_line='800-543-5750', state_id=1),
Mental_Health_Center(name='Central Counties', website='https://www.centralcountiesservices.org/', crisis_line='800-888-4036', state_id=1),
Mental_Health_Center(name='Central Plains', website='http://www.centralplains.org/', crisis_line='800-687-1300', state_id=1),
Mental_Health_Center(name='Coastal Plains', website='http://www.coastalplainsctr.org/', crisis_line='800-841-6467', state_id=1),
Mental_Health_Center(name='Concho Valley', website='https://www.mhmrcv.org/', crisis_line='800-375-8965', state_id=1),
Mental_Health_Center(name='Helen Farabee', website='https://www.helenfarabee.org/', crisis_line='800-621-8504', state_id=1),
Mental_Health_Center(name='Hill Country', website='https://www.hillcountry.org/', crisis_line='877-466-0660', state_id=1),
Mental_Health_Center(name='Lakes Regional', website='https://www.lakesregional.org/', crisis_line='877-466-0660', state_id=1),
Mental_Health_Center(name='Pecan Valley', website='https://www.pecanvalley.org/', crisis_line='800-772-5987', state_id=1),
Mental_Health_Center(name='PermiaCare', website='https://www.pbmhmr.com/', crisis_line='844-420-3964', state_id=1),
Mental_Health_Center(name='StarCare', website='https://www.starcarelubbock.org/', crisis_line='806-740-1414', state_id=1),
Mental_Health_Center(name='Texana', website='https://www.texanacenter.com/', crisis_line='800-633-5686', state_id=1),
Mental_Health_Center(name='Texas Panhandle', website='https://www.texaspanhandlecenters.org/', crisis_line='800-692-4039', state_id=1),
Mental_Health_Center(name='Texoma', website='https://www.texomacc.org/', crisis_line='877-277-2226', state_id=1),
Mental_Health_Center(name='Tri-County', website='http://www.tcmhmrs.org/', crisis_line='800-659-6994', state_id=1),
Mental_Health_Center(name='Tropical', website='http://www.ttbh.org/', crisis_line='877-289-7199', state_id=1),
Mental_Health_Center(name='West Texas', website='https://www.wtcmhmr.org/', crisis_line='800-375-4357', state_id=1),
Mental_Health_Center(name='Gulf Bend Center', website='https://www.gulfbend.org/', crisis_line='877-723-3422', state_id=1),
Mental_Health_Center(name='Burke Center', website='https://www.myburke.org/', crisis_line='800-392-8343', state_id=1),
Mental_Health_Center(name='Spindletop Center', website='http://www.spindletopcenter.org/', crisis_line='800-937-8097', state_id=1),
Mental_Health_Center(name='Gulf Coast Center', website='https://www.gulfcoastcenter.org/', crisis_line='866-729-3848', state_id=1),
Mental_Health_Center(name='LifePath System', website='https://www.lifepathsystems.org/', crisis_line='877-422-5939', state_id=1),
Mental_Health_Center(name='The Center for Healthcare Services', website='https://www.chcsbc.org/', crisis_line='800-316-9241', state_id=1),
Mental_Health_Center(name='Nueces Center for Mental Health', website='https://www.ncmhid.org/', crisis_line='888-767-4493', state_id=1)
]

counties = [
County(state_id=1, name='Anderson'),
County(state_id=1, name='Andrews'),
County(state_id=1, name='Angelina'),
County(state_id=1, name='Aransas'),
County(state_id=1, name='Archer'),
County(state_id=1, name='Armstrong'),
County(state_id=1, name='Atascosa'),
County(state_id=1, name='Austin'),
County(state_id=1, name='Bailey'),
County(state_id=1, name='Bandera'),
County(state_id=1, name='Bastrop'),
County(state_id=1, name='Baylor'),
County(state_id=1, name='Bee'),
County(state_id=1, name='Bell'),
County(state_id=1, name='Bexar'),
County(state_id=1, name='Blanco'),
County(state_id=1, name='Borden'),
County(state_id=1, name='Bosque'),
County(state_id=1, name='Bowie'),
County(state_id=1, name='Brazoria'),
County(state_id=1, name='Brazos'),
County(state_id=1, name='Brewster'),
County(state_id=1, name='Briscoe'),
County(state_id=1, name='Brooks'),
County(state_id=1, name='Brown'),
County(state_id=1, name='Burleson'),
County(state_id=1, name='Burnet'),
County(state_id=1, name='Caldwell'),
County(state_id=1, name='Calhoun'),
County(state_id=1, name='Callahan'),
County(state_id=1, name='Cameron'),
County(state_id=1, name='Camp'),
County(state_id=1, name='Carson'),
County(state_id=1, name='Cass'),
County(state_id=1, name='Castro'),
County(state_id=1, name='Chambers'),
County(state_id=1, name='Cherokee'),
County(state_id=1, name='Childress'),
County(state_id=1, name='Clay'),
County(state_id=1, name='Cochran'),
County(state_id=1, name='Coke'),
County(state_id=1, name='Coleman'),
County(state_id=1, name='Collin'),
County(state_id=1, name='Collingsworth'),
County(state_id=1, name='Colorado'),
County(state_id=1, name='Comal'),
County(state_id=1, name='Comanche'),
County(state_id=1, name='Concho'),
County(state_id=1, name='Cooke'),
County(state_id=1, name='Coryell'),
County(state_id=1, name='Cottle'),
County(state_id=1, name='Crane'),
County(state_id=1, name='Crockett'),
County(state_id=1, name='Crosby'),
County(state_id=1, name='Culberson'),
County(state_id=1, name='Dallam'),
County(state_id=1, name='Dallas'),
County(state_id=1, name='Dawson'),
County(state_id=1, name='Deaf Smith'),
County(state_id=1, name='Delta'),
County(state_id=1, name='Denton'),
County(state_id=1, name='DeWitt'),
County(state_id=1, name='Dickens'),
County(state_id=1, name='Dimmit'),
County(state_id=1, name='Donley'),
County(state_id=1, name='Duval'),
County(state_id=1, name='Eastland'),
County(state_id=1, name='Ector'),
County(state_id=1, name='Edwards'),
County(state_id=1, name='Ellis'),
County(state_id=1, name='El Paso'),
County(state_id=1, name='Erath'),
County(state_id=1, name='Falls'),
County(state_id=1, name='Fannin'),
County(state_id=1, name='Fayette'),
County(state_id=1, name='Fisher'),
County(state_id=1, name='Floyd'),
County(state_id=1, name='Foard'),
County(state_id=1, name='Fort Bend'),
County(state_id=1, name='Franklin'),
County(state_id=1, name='Freestone'),
County(state_id=1, name='Frio'),
County(state_id=1, name='Gaines'),
County(state_id=1, name='Galveston'),
County(state_id=1, name='Garza'),
County(state_id=1, name='Gillespie'),
County(state_id=1, name='Glasscock'),
County(state_id=1, name='Goliad'),
County(state_id=1, name='Gonzales'),
County(state_id=1, name='Gray'),
County(state_id=1, name='Grayson'),
County(state_id=1, name='Gregg'),
County(state_id=1, name='Grimes'),
County(state_id=1, name='Guadalupe'),
County(state_id=1, name='Hale'),
County(state_id=1, name='Hall'),
County(state_id=1, name='Hamilton'),
County(state_id=1, name='Hansford'),
County(state_id=1, name='Hardeman'),
County(state_id=1, name='Hardin'),
County(state_id=1, name='Harris'),
County(state_id=1, name='Harrison'),
County(state_id=1, name='Hartley'),
County(state_id=1, name='Haskell'),
County(state_id=1, name='Hays'),
County(state_id=1, name='Hemphill'),
County(state_id=1, name='Henderson'),
County(state_id=1, name='Hidalgo'	),
County(state_id=1, name='Hill'),
County(state_id=1, name='Hockley'),
County(state_id=1, name='Hood'),
County(state_id=1, name='Hopkins'),
County(state_id=1, name='Houston'),
County(state_id=1, name='Howard'),
County(state_id=1, name='Hudspeth'),
County(state_id=1, name='Hunt'),
County(state_id=1, name='Hutchinson'),
County(state_id=1, name='Irion'),
County(state_id=1, name='Jack'),
County(state_id=1, name='Jackson'),
County(state_id=1, name='Jasper'),
County(state_id=1, name='Jeff Davis'),
County(state_id=1, name='Jefferson'),
County(state_id=1, name='Jim Hogg'),
County(state_id=1, name='Jim Wells'),
County(state_id=1, name='Johnson'),
County(state_id=1, name='Jones'),
County(state_id=1, name='Karnes'),
County(state_id=1, name='Kaufman'),
County(state_id=1, name='Kendall'),
County(state_id=1, name='Kenedy'),
County(state_id=1, name='Kent'),
County(state_id=1, name='Kerr'),
County(state_id=1, name='Kimble'),
County(state_id=1, name='King'),
County(state_id=1, name='Kinney'),
County(state_id=1, name='Kleberg'),
County(state_id=1, name='Knox'),
County(state_id=1, name='Lamar'),
County(state_id=1, name='Lamb'),
County(state_id=1, name='Lampasas'),
County(state_id=1, name='La Salle'),
County(state_id=1, name='Lavaca'),
County(state_id=1, name='Lee'),
County(state_id=1, name='Leon'),
County(state_id=1, name='Liberty'),
County(state_id=1, name='Limestone'),
County(state_id=1, name='Lipscomb'),
County(state_id=1, name='Live Oak'),
County(state_id=1, name='Llano'),
County(state_id=1, name='Loving'),
County(state_id=1, name='Lubbock'),
County(state_id=1, name='Lynn'),
County(state_id=1, name='McCulloch'),
County(state_id=1, name='McLennan'),
County(state_id=1, name='McMullen'),
County(state_id=1, name='Madison'),
County(state_id=1, name='Marion'),
County(state_id=1, name='Martin'),
County(state_id=1, name='Mason'),
County(state_id=1, name='Matagorda'),
County(state_id=1, name='Maverick'),
County(state_id=1, name='Medina'),
County(state_id=1, name='Menard'),
County(state_id=1, name='Midland'),
County(state_id=1, name='Milam'),
County(state_id=1, name='Mills'),
County(state_id=1, name='Mitchell'),
County(state_id=1, name='Montague'),
County(state_id=1, name='Montgomery'),
County(state_id=1, name='Moore'),
County(state_id=1, name='Morris'),
County(state_id=1, name='Motley'),
County(state_id=1, name='Nacogdoches'),
County(state_id=1, name='Navarro'),
County(state_id=1, name='Newton'),
County(state_id=1, name='Nolan'),
County(state_id=1, name='Nueces'),
County(state_id=1, name='Ochiltree'),
County(state_id=1, name='Oldham'),
County(state_id=1, name='Orange'),
County(state_id=1, name='Palo Pinto'),
County(state_id=1, name='Panola'),
County(state_id=1, name='Parker'),
County(state_id=1, name='Parmer'),
County(state_id=1, name='Pecos'),
County(state_id=1, name='Polk'),
County(state_id=1, name='Potter'),
County(state_id=1, name='Presidio'),
County(state_id=1, name='Rains'),
County(state_id=1, name='Randall'),
County(state_id=1, name='Reagan'),
County(state_id=1, name='Real'),
County(state_id=1, name='Red River'),
County(state_id=1, name='Reeves'),
County(state_id=1, name='Refugio'),
County(state_id=1, name='Roberts'),
County(state_id=1, name='Robertson'),
County(state_id=1, name='Rockwall'),
County(state_id=1, name='Runnels'),
County(state_id=1, name='Rusk'),
County(state_id=1, name='Sabine'),
County(state_id=1, name='San Augustine'),
County(state_id=1, name='San Jacinto'),
County(state_id=1, name='San Patricio'),
County(state_id=1, name='San Saba'),
County(state_id=1, name='Schleicher'),
County(state_id=1, name='Scurry'),
County(state_id=1, name='Shackelford'),
County(state_id=1, name='Shelby'),
County(state_id=1, name='Sherman'),
County(state_id=1, name='Smith'),
County(state_id=1, name='Somervell'),
County(state_id=1, name='Starr'),
County(state_id=1, name='Stephens'),
County(state_id=1, name='Sterling'),
County(state_id=1, name='Stonewall'),
County(state_id=1, name='Sutton'),
County(state_id=1, name='Swisher'),
County(state_id=1, name='Tarrant'),
County(state_id=1, name='Taylor'),
County(state_id=1, name='Terrell'),
County(state_id=1, name='Terry'),
County(state_id=1, name='Throckmorton'),
County(state_id=1, name='Titus'),
County(state_id=1, name='Tom Green'),
County(state_id=1, name='Travis'),
County(state_id=1, name='Trinity'),
County(state_id=1, name='Tyler'),
County(state_id=1, name='Upshur'),
County(state_id=1, name='Upton'),
County(state_id=1, name='Uvalde'),
County(state_id=1, name='Val Verde'),
County(state_id=1, name='Van Zandt'),
County(state_id=1, name='Victoria'),
County(state_id=1, name='Walker'),
County(state_id=1, name='Waller'),
County(state_id=1, name='Ward'),
County(state_id=1, name='Washington'),
County(state_id=1, name='Webb'),
County(state_id=1, name='Wharton'),
County(state_id=1, name='Wheeler'),
County(state_id=1, name='Wichita'),
County(state_id=1, name='Wilbarger'),
County(state_id=1, name='Willacy'),
County(state_id=1, name='Williamson'),
County(state_id=1, name='Wilson'),
County(state_id=1, name='Winkler'),
County(state_id=1, name='Wise'),
County(state_id=1, name='Wood'),
County(state_id=1, name='Yoakum'),
County(state_id=1, name='Young'),
County(state_id=1, name='Zapata'),
County(state_id=1, name='Zavala')
]

db.session.bulk_save_objects(mental_health_centers, counties)
db.session.commit()