from crisis_models import Mental_Health_Center, State

State(name='Texas')

Mental_Health_Center(name='Access', website='http://www.accessmhmr.org/', crisis_line='800-621-1693', state_id= 1)
Mental_Health_Center(name='North Texas Behavioral Health Authority', website='https://ntbha.org/', crisis_line='866-260-8000', state_id=1)
Mental_Health_Center(name='Austin Travis County Integral Care', website='https://integralcare.org/en/home/', crisis_line='512-472-4357', state_id=1)
Mental_Health_Center(name='Heart of Texas Region MHMR Center', website='https://www.hotrmhmr.org/', crisis_line='866-752-3451', state_id=1)
Mental_Health_Center(name='MHMR Authority of Brazos Valley', website='https://www.mhmrabv.org/', crisis_line='888-522-8262', state_id=1)
Mental_Health_Center(name='MHMR Authority of Harris County', website='https://www.theharriscenter.org/', crisis_line='866-970-4770', state_id=1)
Mental_Health_Center(name='Center for Life Resources', website='http://www.cflr.us/ns/', crisis_line='800-458-7788', state_id=1)
Mental_Health_Center(name='Denton County MHMR Center', website='http://www.dentonmhmr.org/', crisis_line='800-762-0157', state_id=1)
Mental_Health_Center(name='Emergence Health Network', website='https://www.emergencehealthnetwork.org/', crisis_line='877-562-6467', state_id=1)
Mental_Health_Center(name='MHMR of Tarrant County', website='https://www.mhmrtarrant.org/', crisis_line='800-866-2465', state_id=1)
Mental_Health_Center(name='Community Healthcore', website='http://www.communityhealthcore.com/', crisis_line='800-832-1009', state_id=1)
Mental_Health_Center(name='Andrews Center', website='http://www.andrewscenter.com/', crisis_line='877-934-2131', state_id=1)
Mental_Health_Center(name='Betty Hardwick', website='https://www.bettyhardwick.org/', crisis_line='800-758-3344', state_id=1)
Mental_Health_Center(name='Bluebonnet Trails', website='http://www.bbtrails.org/', crisis_line='800-841-1255', state_id=1)
Mental_Health_Center(name='Border Region', website='http://www.borderregion.org/', crisis_line='800-643-1102', state_id=1)
Mental_Health_Center(name='Camino Real', website='http://www.caminorealcs.org/', crisis_line='800-543-5750', state_id=1)
Mental_Health_Center(name='Central Counties', website='https://www.centralcountiesservices.org/', crisis_line='800-888-4036', state_id=1)
Mental_Health_Center(name='Central Plains', website='http://www.centralplains.org/', crisis_line='800-687-1300', state_id=1)
Mental_Health_Center(name='Coastal Plains', website='http://www.coastalplainsctr.org/', crisis_line='800-841-6467', state_id=1)
Mental_Health_Center(name='Concho Valley', website='https://www.mhmrcv.org/', crisis_line='800-375-8965', state_id=1)
Mental_Health_Center(name='Helen Farabee', website='https://www.helenfarabee.org/', crisis_line='800-621-8504', state_id=1)
Mental_Health_Center(name='Hill Country', website='https://www.hillcountry.org/', crisis_line='877-466-0660', state_id=1)
Mental_Health_Center(name='Lakes Regional', website='https://www.lakesregional.org/', crisis_line='877-466-0660', state_id=1)
Mental_Health_Center(name='Pecan Valley', website='https://www.pecanvalley.org/', crisis_line='800-772-5987', state_id=1)
Mental_Health_Center(name='PermiaCare', website='https://www.pbmhmr.com/', crisis_line='844-420-3964', state_id=1)
Mental_Health_Center(name='StarCare', website='https://www.starcarelubbock.org/', crisis_line='806-740-1414', state_id=1)
Mental_Health_Center(name='Texana', website='https://www.texanacenter.com/', crisis_line='800-633-5686', state_id=1)
Mental_Health_Center(name='Texas Panhandle', website='https://www.texaspanhandlecenters.org/', crisis_line='800-692-4039', state_id=1)
Mental_Health_Center(name='Texoma', website='https://www.texomacc.org/', crisis_line='877-277-2226', state_id=1)
Mental_Health_Center(name='Tri-County', website='http://www.tcmhmrs.org/', crisis_line='800-659-6994', state_id=1)
Mental_Health_Center(name='Tropical', website='http://www.ttbh.org/', crisis_line='877-289-7199', state_id=1)
Mental_Health_Center(name='West Texas', website='https://www.wtcmhmr.org/', crisis_line='800-375-4357', state_id=1)
Mental_Health_Center(name='Gulf Bend Center', website='https://www.gulfbend.org/', crisis_line='877-723-3422', state_id=1)
Mental_Health_Center(name='Burke Center', website='https://www.myburke.org/', crisis_line='800-392-8343', state_id=1)
Mental_Health_Center(name='Spindletop Center', website='http://www.spindletopcenter.org/', crisis_line='800-937-8097', state_id=1)
Mental_Health_Center(name='Gulf Coast Center', website='https://www.gulfcoastcenter.org/', crisis_line='866-729-3848', state_id=1)
Mental_Health_Center(name='LifePath System', website='https://www.lifepathsystems.org/', crisis_line='877-422-5939', state_id=1)
Mental_Health_Center(name='The Center for Healthcare Services', website='https://www.chcsbc.org/', crisis_line='800-316-9241', state_id=1)
Mental_Health_Center(name='Nueces Center for Mental Health', website='https://www.ncmhid.org/', crisis_line='888-767-4493', state_id=1)